FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
  python3 \
  python-is-python3 \
  python3-pip \
  python3-venv \
  build-essential \
  cmake \
  && rm -rf /var/lib/apt/lists/*
